apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagex-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swagex-app
  template:
    metadata:
      labels:
        app: swagex-app
    spec:
      containers:
        - name: swagex-app
          image: registry.digitalocean.com/swagex
          ports:
            - containerPort: 3000
