name: Swagex DigitalOcean Kubernetes Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - 'k8s/**'
      - 'Dockerfile'
      - '.github/workflows/**'
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build container image
      run: docker build -t registry.digitalocean.com/registry.digitalocean.com/swagex/swagex-app:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    
    - name: Remove all old images
      run: |
        if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then
          TAGS=$(doctl registry repository list-tags $(echo $IMAGE_NAME) --format "Tag" --no-header)
          for TAG in $TAGS; do
            if [ "$TAG" != "latest" ]; then
              doctl registry repository delete-manifest $(echo $IMAGE_NAME) $TAG --force
            fi
          done
        else
          echo "No repository"
        fi


    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/registry.digitalocean.com/swagex/swagex-app:$(echo $GITHUB_SHA | head -c7)
