name: Swagex DigitalOcean Kubernetes Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - 'k8s/**'
      - 'Dockerfile'
      - '.github/workflows/**'
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build container image
      run: docker build -t registry.digitalocean.com/registry.digitalocean.com/swagex/swagex-app:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/registry.digitalocean.com/swagex/swagex-app:$(echo $GITHUB_SHA | head -c7)
