name: SWagex CI Digital Ocean Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      # Your other build and test steps go here

    - name: Restart Node.js Application
      run: |
        # Assuming your app is managed by PM2
        pm2 restart src/app.js
      working-directory: ~/root/actions-runner/_work/express-swagger-setup/express-swagger-setup/

      
