name: Build, push, and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'src/**'  # Update the path to your source code directory
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container image
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          docker build -t registry.digitalocean.com/registry.digitalocean.com/swagex/swagex-app:${TAG} .
          echo $TAG >> $GITHUB_ENV
        shell: bash

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/registry.digitalocean.com/swagex/swagex-app:${{ env.TAG }}

      - name: Update deployment file
      run: |
        kubectl apply -f $GITHUB_WORKSPACE/k8s/deployment.yml
        kubectl apply -f $GITHUB_WORKSPACE/k8s/service.yml
        shell: bash

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 your-cluster-name

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml

      - name: Verify deployment
        run: kubectl rollout status deployment/your-app-name
